Application:
  # The name of the project
  name: ProjectName
  
  # The webRoot of the project.
  # If you access the website as "http://localhost/ProjectName/", then "ProjectName/" is your webRoot
  # If you access the website as "http://localhost/", then "" is your webRoot
  webRoot: "ProjectName/"
  
  # Database configuratoin
  database:
    driver: pdo_mysql
    host: localhost
    port: 3306
    name: databaseName
    user: databaseUser
    password: databasePassword

  compiler:
    exclude:
      - "/.buildpath"
      - "/.project"
      - "/.settings"
      - "/*.phar"
      - "/.git"
      - "/.htaccess"
      - "/*.md"
      - "/*.markdown"
      - "/test/"
      - "/tests/"
      - "/Test/"
      - "/Tests/"
      - "/LICENSE"
      - "/build.properties"

  webServer:
    parsables:
      - html
      - xml
      - xhtml
      - js
      - json
      - yaml
      - yml
